#
# Module manifest for module 'PSGet_ChocoMan'
#
# Generated by: regg00
#
# Generated on: 2025-08-01
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\ChocoMan.psm1'

# Version number of this module.
ModuleVersion = '1.3.5'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a1f003a9-6a9c-4d83-a6ae-b857b91f766d'

# Author of this module
Author = 'regg00'

# Company or vendor of this module
CompanyName = 'RLConsulting'

# Copyright statement for this module
Copyright = '(c) regg00. All rights reserved.'

# Description of the functionality provided by this module
Description = '![Tests](https://github.com/regg00/ChocoMan/actions/workflows/test-and-deploy.yaml/badge.svg)
![Docs](https://github.com/regg00/ChocoMan/actions/workflows/build-doc.yaml/badge.svg)
[![GitHub issues](https://img.shields.io/github/issues/regg00/ChocoMan.svg)](https://github.com/regg00/ChocoMan/issues)

<img src="./Docs/icon.png" height="200">

# ChocoMan

A PowerShell wrapper around Chocolatey.

## Why it exists

Mostly for fun, but I also got tired of parsing raw output of Chocolatey commands in my deployment scripts. I figured having each command outputs a standardized PowerShell object would help somehow.

## Installing this module

This module is available in [PowerShell Gallery](https://www.powershellgallery.com/packages/ChocoMan):

```powershell
Install-Module ChocoMan
```

Or, download it from here and save all of the files somewhere in your `$PSModulePath`.

## Before you start

Before using this package, you need to make sure that Chocolatey is installed on your device.

You can valide this with the `choco --version` command.

```powershell
PS C:\> choco --version
2.1.0
```

You can also install it using this module with the `Install-Choco` command.

```powershell
PS C:\> Install-Choco
Chocolatey v2.1.0 installed
```

## Using the module

First things first, you need to import it `Import-Module ChocoMan`

## Hide the activity indicator

The activity indicator can be hidden by setting the `ProgressPreference` variable to `SilentlyContinue`

```powershell
PS C:\> Set-Variable ProgressPreference SilentlyContinue ; Get-ChocoOutdated
```

### Demo

<img src="./Docs/demo.gif" height="500">

### Functions

Here''s the status of each functions:

| Command                                                    | Status             | Notes                                                                              |
| ---------------------------------------------------------- | ------------------ | ---------------------------------------------------------------------------------- |
| [Get-ChocoApiKey](./Docs/Get-ChocoApiKey.md)               | :white_check_mark: | Retrieves, saves or deletes an API key for a particular source                     |
| [Get-ChocoConfig ](./Docs/Get-ChocoConfig.md)              | :white_check_mark: | Retrieves the chocolatey configuration                                             |
| [Get-ChocoFeature ](./Docs/Get-ChocoFeature.md)            | :white_check_mark: | Retrieves the chocolatey features                                                  |
| [Get-ChocoOutdated](./Docs/Get-ChocoOutdated.md)           | :white_check_mark: | Get the list of outdated chocolatey packages.                                      |
| [Get-ChocoPackage](./Docs/Get-ChocoPackage.md)             | :white_check_mark: | Get a specific locally installed chocolatey package.                               |
| [Get-ChocoSources](./Docs/Get-ChocoSources.md)             | :white_check_mark: | Get the list of chocolatey sources.                                                |
| [Get-ChocoVersion](./Docs/Get-ChocoVersion.md)             | :white_check_mark: | Get the version of chocolatey.                                                     |
| [Get-ChocoManVersion](./Docs/Get-ChocoManVersion.md)       | :white_check_mark: | Get the version of ChocoMan.                                                       |
| [Get-ChocoPackageInfo](./Docs/Get-ChocoPackageInfo.md)     | :white_check_mark: | Get information on an existing package.                                            |
| [Set-ChocoApiKey](./Docs/Set-ChocoApikey.md)               | :white_check_mark: | Edit API keys                                                                      |
| [Set-ChocoConfig](./Docs/Set-ChocoConfig.md)                                            | :white_check_mark: | Edit chocolatey configuration                                                      |
| [Search-ChocoPackage](./Docs/Search-ChocoPackage.md)       | :white_check_mark: | Search for a choco'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-ChocoVersion', 'Get-ChocoPackages', 'Get-ChocoPackage', 
               'Get-ChocoOutdated', 'Get-ChocoSource', 'Search-ChocoPackage', 
               'Install-Choco', 'Install-ChocoPackage', 'Get-ChocoApiKey', 
               'Set-ChocoApiKey', 'Add-ChocoSource', 'Remove-ChocoSource', 
               'Get-ChocoConfig', 'Get-ChocoFeature', 'Uninstall-ChocoPackage', 
               'Update-ChocoPackage', 'Get-ChocoManVersion', 'Get-ChocoPackageInfo', 
               'Set-ChocoConfig', 'New-ChocoPackage', 'Export-ChocoPackage'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Add-ChocoApiKey'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Chocolatey','Package','Management','Windows'

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/regg00/ChocoMan'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/regg00/ChocoMan/refs/heads/main/Docs/icon.png'

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

