name: Build documentation

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
  push:
    branches:
      - main
    paths-ignore:
      - "Docs/**"

jobs:
  build-doc:
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Build documentation
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name platyPS -Scope CurrentUser
          Import-Module platyPS
          Import-Module .\ChocoMan.psd1 -Force
          New-MarkdownHelp -module ChocoMan -OutputFolder .\Docs\ -Force -AlphabeticParamsOrder

      - name: Commit and push changes
        if: github.event_name == 'push'
        run: |
          git config --global user.name "CI"
          git config --global user.email "regg00@gmail.com"
          git commit -a -m "Updated documentation"
          git push
